# Generated by Django 2.2.12 on 2021-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('PGN', models.CharField(max_length=20000)),
                ('black', models.CharField(max_length=200)),
                ('white', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=500)),
            ],
        ),
    ]
