# Generated by Django 2.2.12 on 2021-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chessapp", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="game", name="outcome"),
        migrations.AddField(
            model_name="game",
            name="black_level",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="white_level",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
