docker-compose down --remove-orphans && \
	docker-compose build && \
	echo "from chessapp.models import Game"
	echo "from chessapp.serializers import GameSerializer"
	echo "from rest_framework.renderers import JSONRenderer"
	echo "from rest_framework.parsers import JSONParser"
	echo "game = Game(title='test')"
	echo "game.save()"
	echo "serializer = GameSerializer(game)"
	echo "serializer.data"
	echo "content = JSONRenderer().render(serializer.data)"
	echo "content"
	echo "import io"
	echo "stream = io.BytesIO(content)"
	echo "data = JSONParser().parse(stream)"
	echo "data"
	echo "serializer = GameSerializer(data=data)"
	echo "serializer.is_valid()"
	echo "serializer.validated_data"
	echo "serializer.save()"
	echo "serializer = GameSerializer(Game.objects.all(), many=True)"
	echo "serializer.data"
	echo "history"
	docker-compose run api python3 manage.py shell
