# Generated by Django 3.1.13 on 2021-09-29 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 0, 24, 48, 560300, tzinfo=utc)),
        ),
    ]
