# Generated by Django 3.1.13 on 2021-09-29 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_auto_20210928_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 0, 26, 19, 232208, tzinfo=utc)),
        ),
    ]
